### ISSUE TITLE
Ubtuntu 17.10 x64 | GCC 7.2 Build Issues & Solution

### ISSUE THREAD

**Issue by oDinZu** [bitcoinhush/bitcoinhush#5]
If having trouble compiling with ./zcutil/build.sh -j2 on Ubuntu 17.10, this quick fix and 3 file edits done the trick for me. 
 #zcash https://github.com/zcash/zcash/pull/2545/files

I am not 100% but it seems the build.sh was built for a older version of GCC5-6. You can read more at the link provided if you would like to learn more.

**Comment by leto** [comment]
@csharpee i have never tested on 17.10 and it's not supported anymore, but I am open to supporting GCC 7, that seems reasonable

**Comment by leto** [comment]
just saw this was from 2018 :smile:

**Comment by akirax82** [comment]
Thank you for revisiting Bitcoin hush

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
